### ISSUE TITLE
Whitelisting not working

### ISSUE THREAD

**Issue by PersuGames** [Benjamin-Norton/AllTheTrims#14]
https://github.com/Bawnorton/AllTheTrims/wiki/Whitelisting
Following this wiki page, I tried enabling a whitelist.
When the whitelist is not ignored even vanilla mats don't work.
The file and folders with this address (*\Modpack\data\allthetrims\tags\items\whitelist.json) weren't there.
When I added them manually and pasted the example code in the whitelist file I couldn't use the example minecraft:stone to work either.
After every change I restarted Minecraft entirely just to make sure it had it's time to load. Is this a bug or am I doing something wrong?
I'm playing on the newest version of the mod.

**Comment by Bawnorton** [comment]
I haven't actually tested the whitelisting system in a while, so I may have broken it at some point. I'll give it a look when I'm not busy.

**Comment by Ultimushadow** [comment]
I can confirm that the whitelist still isn't working. I first tried adding the whitelist with no items/one item, but it broke the trim entirely and nothing could be trimmed. Then, I tried adding all the vanilla, modded, and datapack items I have on my game to the whitelist. This was, really weird, as half of them don't render and half of them do. The modded items were the smallest sample size at 3 and they all were included as trim already so I don't know why they had no texture. Half the vanilla trims had not texture, and half the datapack items (which were vanilla but not vanilla trim) worked though. 
All of the items that weren't missing texture blocks also had no dynamically rendered item texture from Dynamic Trims either.

**Comment by Bawnorton** [comment]
I'm gonna can the whitelisting, it doesn't really fit with the mod and is proving to be quite the headache to fix with the limited amount of time I have at the moment. 
Sorry, I may come back to it in the future but it's pretty low on my list of priorities atm as very few people are actively using it.

**Comment by Ultimushadow** [comment]
Ah, that's rough. I think that the whitelist feature was nice because it separated two parts of what the mod accomplishes, making everything a trim but also automatically making trim textures and working with modded armor and armor trims. The whitelist helped to isolate that latter part, and now that it's being discontinued it looks like there isn't really anything that has that feature in the current ecosystem.
I hope you're able to figure it out when you have more time/motivation to throw at a smaller part of the mod like this, although it's not useful for the general public it's definitely invaluable for pack makers at any level
Either way, I do appreciate the work that went in trying to get the feature functional
